source(file.path(Sys.getenv("SCRIPT_DIR"), "amp_common.R"), encoding = "UTF-8")
params <- read_amp_params()
ctx <- init_amp_context(params, "07_machine_learning", "machine_learning_results.xlsx")
otu <- as(phyloseq::otu_table(ctx$ps), "matrix")
if (phyloseq::taxa_are_rows(ctx$ps)) otu <- t(otu)
otu <- log1p(sweep(otu, 1, pmax(rowSums(otu), 1), "/") * 1e6)
fit <- stats::prcomp(otu, center = TRUE, scale. = TRUE)
loadings <- data.frame(feature = rownames(fit$rotation), fit$rotation, check.names = FALSE)
top <- head(loadings[order(abs(loadings$PC1), decreasing = TRUE), ], param_int(params, "top_n", 20))
p <- ggplot2::ggplot(top, ggplot2::aes(stats::reorder(feature, abs(PC1)), PC1, fill = PC1 > 0)) +
  ggplot2::geom_col(show.legend = FALSE) + ggplot2::coord_flip() +
  ggplot2::labs(title = "PCA feature loadings", x = NULL, y = "PC1 loading") + theme_nature()
save_plot2(p, ctx$out_dir, "loading_pca", width = 9, height = 7)
write_sheet2(ctx$workbook, "PCA_loadings", loadings)
save_amp_workbook(ctx)
